language: python
sudo: false

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="django==1.8.6"
  - DJANGO="https://www.djangoproject.com/download/1.9b1/tarball/"

install:
  - pip install $DJANGO
  - pip install jinja2 django-pipeline
  - pip install pytz

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="https://www.djangoproject.com/download/1.9b1/tarball/"

script:
  - cd testing && python runtests.py

notifications:
  email:
    recipients:
      - niwi@niwi.nz
    on_success: change
    on_failure: change
