language: python
sudo: false

python:
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="django==1.8.0"

install:
  - pip install $DJANGO
  - pip install jinja2 django-pipeline
  - pip install pytz
script:
  - cd testing && python runtests.py

notifications:
  email:
    recipients:
      - niwi@niwi.nz
    on_success: change
    on_failure: change
